Repository pyiron/pyiron_contrib, pull requests merged in 2021-08, with the labels that each got.

#219 Add convenience from lammps potentials to Mlip job
  pyiron_contrib/atomistics/mlip/mlip.py
Labels: enhancement

#220 Allow number as potential input for Mlip jobs
  pyiron_contrib/atomistics/mlip/mlip.py
Labels: enhancement

#226 Bump pyiron_base to 0.2.24 and pyiron_atomistics to 0.2.23
  .ci_support/environment.yml
  setup.py
Labels: dependencies

#218 Force cells and pbcs to be saved per chunk and add test
  pyiron_contrib/atomistics/atomistics/job/structurestorage.py
  tests/atomistics/job/test_structurestorage.py
Labels: bug, enhancement

#211 Use StructureStorage instead of DataContainer for structures in RandSpg
  pyiron_contrib/atomistics/randspg/randspg.py
Labels: enhancement, broken compatibility
