Repository pyiron/pyiron_contrib, pull requests merged in 2023-06, with the labels that each got.

#715 Add calc static
  pyiron_contrib/workflow/node_library/atomistics.py
  pyiron_contrib/workflow/workflow.py
Labels: format_black

#724 Add server object to Node and Workflow
  pyiron_contrib/workflow/node.py
  pyiron_contrib/workflow/workflow.py
Labels: enhancement, format_black

#727 Has nodes mixin
  pyiron_contrib/tinybase/task.py
  pyiron_contrib/workflow/has_nodes.py
  pyiron_contrib/workflow/node.py
  pyiron_contrib/workflow/node_library/package.py
  pyiron_contrib/workflow/workflow.py
  tests/unit/workflow/test_node_package.py
  tests/unit/workflow/test_workflow.py
Labels: format_black

#732 Workflow: Refactor io
  pyiron_contrib/workflow/io.py
Labels: format_black

#735 Workflow: Better io
  pyiron_contrib/workflow/channels.py
  pyiron_contrib/workflow/io.py
  tests/unit/workflow/test_io.py
Labels: format_black

#725 Introduce DirectoryObject and FileObject in Workflow
  pyiron_contrib/workflow/files.py
  pyiron_contrib/workflow/node.py
  pyiron_contrib/workflow/workflow.py
  tests/unit/workflow/test_files.py
  tests/unit/workflow/test_node.py
  tests/unit/workflow/test_workflow.py
Labels: enhancement, format_black

#730 Add pympipool executor
  .binder/environment.yml
  .ci_support/environment.yml
  docs/environment.yml
  pyiron_contrib/tinybase/executor.py
  setup.py
Labels: enhancement, format_black

#753 Update docs
  pyiron_contrib/workflow/function.py
  pyiron_contrib/workflow/node.py
Labels: .workflow

#755 Fast by default
  notebooks/workflow_example.ipynb
  pyiron_contrib/workflow/composite.py
  pyiron_contrib/workflow/function.py
  pyiron_contrib/workflow/node_library/atomistics.py
  pyiron_contrib/workflow/workflow.py
  tests/unit/workflow/test_function.py
  tests/unit/workflow/test_node_package.py
  tests/unit/workflow/test_workflow.py
Labels: .workflow

#754 Data channel value starts as not data
  notebooks/workflow_example.ipynb
  pyiron_contrib/workflow/channels.py
  pyiron_contrib/workflow/composite.py
  pyiron_contrib/workflow/function.py
  pyiron_contrib/workflow/node_library/atomistics.py
  pyiron_contrib/workflow/workflow.py
  tests/unit/workflow/test_channels.py
  tests/unit/workflow/test_function.py
  tests/unit/workflow/test_node_package.py
  tests/unit/workflow/test_workflow.py
Labels: .workflow

#751 Rename classes
  notebooks/workflow_example.ipynb
  pyiron_contrib/workflow/channels.py
  pyiron_contrib/workflow/composite.py
  pyiron_contrib/workflow/function.py
  pyiron_contrib/workflow/is_nodal.py
  pyiron_contrib/workflow/node.py
  pyiron_contrib/workflow/node_library/atomistics.py
  pyiron_contrib/workflow/node_library/package.py
  pyiron_contrib/workflow/node_library/standard.py
  pyiron_contrib/workflow/workflow.py
  tests/unit/workflow/test_channels.py
  tests/unit/workflow/test_function.py
  tests/unit/workflow/test_node_package.py
  tests/unit/workflow/test_workflow.py
Labels: .workflow

#750 Fix type hints
  notebooks/workflow_example.ipynb
  pyiron_contrib/workflow/channels.py
  pyiron_contrib/workflow/composite.py
  pyiron_contrib/workflow/function.py
  pyiron_contrib/workflow/is_nodal.py
  pyiron_contrib/workflow/node.py
  pyiron_contrib/workflow/node_library/atomistics.py
  pyiron_contrib/workflow/node_library/package.py
  pyiron_contrib/workflow/node_library/standard.py
  pyiron_contrib/workflow/workflow.py
  tests/unit/workflow/test_channels.py
  tests/unit/workflow/test_function.py
  tests/unit/workflow/test_node_package.py
  tests/unit/workflow/test_workflow.py
Labels: .workflow

#748 Workflow: Composition to inheritance
  notebooks/workflow_example.ipynb
  pyiron_contrib/workflow/channels.py
  pyiron_contrib/workflow/composite.py
  pyiron_contrib/workflow/function.py
  pyiron_contrib/workflow/is_nodal.py
  pyiron_contrib/workflow/node.py
  pyiron_contrib/workflow/node_library/atomistics.py
  pyiron_contrib/workflow/node_library/package.py
  pyiron_contrib/workflow/node_library/standard.py
  pyiron_contrib/workflow/workflow.py
  tests/unit/workflow/test_channels.py
  tests/unit/workflow/test_function.py
  tests/unit/workflow/test_node_package.py
  tests/unit/workflow/test_workflow.py
Labels: .workflow
