Repository pyiron/pyiron_contrib, pull requests merged in 2024-02, with the labels that each got.

#978 Update shell notebook
  notebooks/tinybase/Shell.ipynb
  pyiron_contrib/atomistics/atomicrex/potential_factory.py
  pyiron_contrib/atomistics/atomicrex/structure_list.py
  pyiron_contrib/atomistics/interactive/montecarlo.py
  pyiron_contrib/atomistics/lammps/drag.py
  pyiron_contrib/atomistics/meamfit/meamfit.py
  pyiron_contrib/atomistics/runner/storageclasses.py
  pyiron_contrib/protocol/utils/pptree.py
  pyiron_contrib/tinybase/lammps.py
  pyiron_contrib/tinybase/murn.py
  pyiron_contrib/tinybase/shell.py
Labels: format_black

#968 Lighten the import of pyiron_contrib
  notebooks/coscine_io.ipynb
  pyiron_contrib/RDM/__init__.py
  pyiron_contrib/__init__.py
  tests/unit/RDM/test_storagejob.py
Labels: broken compatibility

#995 Remove potential fitting jobs
  pyiron_contrib/__init__.py
  pyiron_contrib/atomistics/atomicrex/__init__.py
  pyiron_contrib/atomistics/atomicrex/atomicrex_job.py
  pyiron_contrib/atomistics/atomicrex/base.py
  pyiron_contrib/atomistics/atomicrex/fit_properties.py
  pyiron_contrib/atomistics/atomicrex/function_factory.py
  pyiron_contrib/atomistics/atomicrex/general_input.py
  pyiron_contrib/atomistics/atomicrex/interactive.py
  pyiron_contrib/atomistics/atomicrex/output.py
  pyiron_contrib/atomistics/atomicrex/parameter_constraints.py
  pyiron_contrib/atomistics/atomicrex/potential_factory.py
  pyiron_contrib/atomistics/atomicrex/structure_list.py
  pyiron_contrib/atomistics/atomicrex/utility_functions.py
  pyiron_contrib/atomistics/atomistics/job/__init__.py
  pyiron_contrib/atomistics/atomistics/job/trainingcontainer.py
  pyiron_contrib/atomistics/fitsnap/__init__.py
  pyiron_contrib/atomistics/fitsnap/common.py
  pyiron_contrib/atomistics/fitsnap/job.py
  pyiron_contrib/atomistics/meamfit/meamfit.py
  pyiron_contrib/atomistics/ml/__init__.py
  pyiron_contrib/atomistics/ml/potentialfit.py
  pyiron_contrib/atomistics/mlip/__init__.py
  pyiron_contrib/atomistics/mlip/cfgs.py
  pyiron_contrib/atomistics/mlip/lammps.py
  pyiron_contrib/atomistics/mlip/masters.py
  pyiron_contrib/atomistics/mlip/mlip.py
  pyiron_contrib/atomistics/mlip/mlipdescriptors.py
  pyiron_contrib/atomistics/mlip/mlipjob.py
  pyiron_contrib/atomistics/mlip/mlipselect.py
  pyiron_contrib/atomistics/mlip/parser.py
  pyiron_contrib/atomistics/mlip/potential.py
  pyiron_contrib/atomistics/pacemaker/__init__.py
  pyiron_contrib/atomistics/pacemaker/job.py
  pyiron_contrib/atomistics/runner/__init__.py
  pyiron_contrib/atomistics/runner/job.py
  pyiron_contrib/atomistics/runner/storageclasses.py
  pyiron_contrib/atomistics/runner/utils.py
  tests/unit/atomistics/job/__init__.py
  tests/unit/atomistics/job/test_trainingcontainer.py
  tests/unit/atomistics/mlip/__init__.py
  tests/unit/atomistics/mlip/test_parser.py
Labels: enhancement, format_black
